// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlcgen

type Session struct {
	ID        string
	UserID    int64
	ExpiresAt string
	CreatedAt string
}

type User struct {
	ID             int64
	Username       string
	PasswordHash   string
	TotpSecret     string
	TotpEnabled    bool
	FailedAttempts int64
	LockedUntil    *string
	CreatedAt      string
	LastLoginAt    *string
}
