// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package sqlcgen

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, password_hash)
VALUES (?1, ?2)
RETURNING id
`

type CreateUserParams struct {
	Username     string
	PasswordHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Username, arg.PasswordHash)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id,
       username,
       password_hash,
       totp_secret,
       totp_enabled,
       failed_attempts,
       locked_until,
       created_at,
       last_login_at
FROM users
WHERE username = ?1
LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.FailedAttempts,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const resetFailedAttempts = `-- name: ResetFailedAttempts :exec
UPDATE users
SET failed_attempts = 0,
    locked_until = NULL
WHERE id = ?1
`

func (q *Queries) ResetFailedAttempts(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, resetFailedAttempts, id)
	return err
}

const setTOTPSecret = `-- name: SetTOTPSecret :exec
UPDATE users
SET totp_secret = ?1,
    totp_enabled = ?2
WHERE id = ?3
`

type SetTOTPSecretParams struct {
	TotpSecret  string
	TotpEnabled bool
	ID          int64
}

func (q *Queries) SetTOTPSecret(ctx context.Context, arg SetTOTPSecretParams) error {
	_, err := q.db.ExecContext(ctx, setTOTPSecret, arg.TotpSecret, arg.TotpEnabled, arg.ID)
	return err
}

const updateFailedAttempts = `-- name: UpdateFailedAttempts :exec
UPDATE users
SET failed_attempts = ?1,
    locked_until = ?2
WHERE id = ?3
`

type UpdateFailedAttemptsParams struct {
	FailedAttempts int64
	LockedUntil    *string
	ID             int64
}

func (q *Queries) UpdateFailedAttempts(ctx context.Context, arg UpdateFailedAttemptsParams) error {
	_, err := q.db.ExecContext(ctx, updateFailedAttempts, arg.FailedAttempts, arg.LockedUntil, arg.ID)
	return err
}

const updateLastLogin = `-- name: UpdateLastLogin :exec
UPDATE users
SET last_login_at = ?1
WHERE id = ?2
`

type UpdateLastLoginParams struct {
	LastLoginAt *string
	ID          int64
}

func (q *Queries) UpdateLastLogin(ctx context.Context, arg UpdateLastLoginParams) error {
	_, err := q.db.ExecContext(ctx, updateLastLogin, arg.LastLoginAt, arg.ID)
	return err
}
